apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: omni-gitops-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: omni-gitops-controller
subjects:
  - kind: ServiceAccount
    name: omni-gitops-controller
    namespace: omni-gitops-system
