//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ConfigPatch) DeepCopyInto(out *ConfigPatch) {
	*out = *in
	in.Inline.DeepCopyInto(&out.Inline)
}

func (in *ConfigPatch) DeepCopy() *ConfigPatch {
	if in == nil {
		return nil
	}
	out := new(ConfigPatch)
	in.DeepCopyInto(out)
	return out
}

func (in *MachineSetSpec) DeepCopyInto(out *MachineSetSpec) {
	*out = *in
	in.MachineSelector.DeepCopyInto(&out.MachineSelector)
	if in.MachineExtensions != nil {
		in, out := &in.MachineExtensions, &out.MachineExtensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KernelArgs != nil {
		in, out := &in.KernelArgs, &out.KernelArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigPatches != nil {
		in, out := &in.ConfigPatches, &out.ConfigPatches
		*out = make([]ConfigPatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MachineSetSpec) DeepCopy() *MachineSetSpec {
	if in == nil {
		return nil
	}
	out := new(MachineSetSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *WorkerMachineSetSpec) DeepCopyInto(out *WorkerMachineSetSpec) {
	*out = *in
	in.MachineSetSpec.DeepCopyInto(&out.MachineSetSpec)
}

func (in *WorkerMachineSetSpec) DeepCopy() *WorkerMachineSetSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerMachineSetSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OmniClusterSpec) DeepCopyInto(out *OmniClusterSpec) {
	*out = *in
	in.ControlPlane.DeepCopyInto(&out.ControlPlane)
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]WorkerMachineSetSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OmniClusterSpec) DeepCopy() *OmniClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OmniClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OmniClusterStatus) DeepCopyInto(out *OmniClusterStatus) {
	*out = *in
	if in.AllocatedMachines != nil {
		in, out := &in.AllocatedMachines, &out.AllocatedMachines
		*out = make(map[string][]string, len(*in))
		for k, v := range *in {
			var outv []string
			if v != nil {
				outv = make([]string, len(v))
				copy(outv, v)
			}
			(*out)[k] = outv
		}
	}
	if in.FailureReason != nil {
		x := *in.FailureReason
		out.FailureReason = &x
	}
	if in.FailureMessage != nil {
		x := *in.FailureMessage
		out.FailureMessage = &x
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OmniClusterStatus) DeepCopy() *OmniClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OmniClusterStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *OmniCluster) DeepCopyInto(out *OmniCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *OmniCluster) DeepCopy() *OmniCluster {
	if in == nil {
		return nil
	}
	out := new(OmniCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *OmniCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OmniClusterList) DeepCopyInto(out *OmniClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OmniCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OmniClusterList) DeepCopy() *OmniClusterList {
	if in == nil {
		return nil
	}
	out := new(OmniClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *OmniClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
